### ISSUE TITLE
different toggle button icon

### ISSUE THREAD

**Issue by sgratzl** [jsmnbom/githubbotrevised#10]
in the dark mode of Telegram the check mark icons are very hard to read. A simple check icon that uses the same color as the text would create a better contrast. 

![image](https://user-images.githubusercontent.com/4129778/54590739-105aa000-4a29-11e9-8363-73dfbb36e957.png)

**Comment by jsmnbom** [comment]
What icon/emoji would you suggest was used instead?

**Comment by sgratzl** [comment]
what about https://emojipedia.org/ballot-box-with-check/ ☑️

**Comment by jsmnbom** [comment]
Hmm, that's probably a good option yea :)
